/**
 * compliant-token-full Contract Integration Examples
 *
 * Generated by Compact Circuit Analyzer
 * Generated: 6/12/2026, 9:04:57 AM
 * Compiler: 0.5.1
 *
 * These examples show how to interact with the compliant-token-full contract
 * using the Midnight.js SDK.
 */

import {
  createBalancedTx,
  type Contract,
  type ContractAddress,
  deployContract,
  findDeployedContract,
  providers
} from '@midnight-ntwrk/midnight-js-contracts';
import {
  type PrivateStateProvider,
  type PublicDataProvider,
  type ProofProvider,
  type WalletProvider
} from '@midnight-ntwrk/midnight-js-types';
import { NodeProvider } from '@midnight-ntwrk/midnight-js-node-provider';
import { IndexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { HttpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { LevelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';

// Import generated contract artifacts
import contract from './compliant-token-full';

// ============================================================================
// Setup and Configuration
// ============================================================================

/**
 * Network configuration
 */
const NETWORK_CONFIG = {
  // Local development node
  local: {
    nodeUrl: 'ws://localhost:9944',
    indexerUrl: 'http://localhost:8088/graphql',
    proofServerUrl: 'http://localhost:6300'
  },
  // QANet test network
  qanet: {
    nodeUrl: 'wss://qanet-node.midnight.network',
    indexerUrl: 'https://qanet-indexer.midnight.network/graphql',
    proofServerUrl: 'https://qanet-proof-server.midnight.network'
  }
};

// Select network (change as needed)
const network = NETWORK_CONFIG.local;

/**
 * Initialize Midnight.js providers
 */
async function initializeProviders(): Promise<{
  nodeProvider: NodeProvider;
  publicDataProvider: PublicDataProvider;
  privateStateProvider: PrivateStateProvider;
  proofProvider: ProofProvider;
}> {
  // Connect to Midnight node
  const nodeProvider = await NodeProvider.create(network.nodeUrl);

  // Setup public data provider (indexer)
  const publicDataProvider = new IndexerPublicDataProvider(
    network.indexerUrl,
    { timeout: 30000 }
  );

  // Setup private state storage (using LevelDB)
  const privateStateProvider = new LevelPrivateStateProvider({
    storePath: './.midnight-private-state'
  });

  // Setup proof server connection
  const proofProvider = new HttpClientProofProvider(
    network.proofServerUrl,
    { timeout: 120000 } // Proving can take time
  );

  return {
    nodeProvider,
    publicDataProvider,
    privateStateProvider,
    proofProvider
  };
}

// ============================================================================
// Circuit: initializeToken
// ============================================================================

/**
 * Call initializeToken circuit
 * @param name_ - Opaque<"string">
 * @param symbol_ - Opaque<"string">
 * @param decimals_ - Uint<8>
 * @param domain - 32-byte value
 * @returns No return value
 */
async function callInitializeToken(
  contractAddress: ContractAddress,
  walletProvider: WalletProvider,
  name_: string,
  symbol_: string,
  decimals_: any,
  domain: string
): Promise<void> {
  const providers = await initializeProviders();

  try {
    // Create transaction calling initializeToken
    const tx = await createBalancedTx(
      walletProvider,
      providers.privateStateProvider,
      {
        type: 'call-circuit',
        contract: contractAddress,
        circuit: 'initializeToken',
        args: {
          name_,
          symbol_,
          decimals_,
          domain
        }
      },
      providers.publicDataProvider,
      providers.proofProvider
    );

    // Submit transaction to network
    await providers.nodeProvider.submitTx(tx);

    console.log(`✅ initializeToken transaction submitted`);

    // Wait for transaction confirmation
    const result = await providers.publicDataProvider.waitForTx(tx.txHash);

    console.log(`✅ initializeToken confirmed in block ${result.blockHeight}`);

    return result.output;
  } finally {
    await providers.nodeProvider.close();
  }
}

/**
 * Example usage: initializeToken
 */
async function exampleInitializeToken() {
  const name_ = "example"; // Opaque<"string">
  const symbol_ = "example"; // Opaque<"string">
  const decimals_ = /* TODO: provide value */; // Uint<8>
  const domain = 0x0000000000000000000000000000000000000000000000000000000000000000; // Bytes<32>

  // Assuming contract is already deployed
  const contractAddress = 'contract1...'; // Replace with actual address

  // Setup wallet provider (see wallet setup section)
  const walletProvider = await setupWallet();

  const result = await callInitializeToken(
    contractAddress,
    walletProvider,
    name_, symbol_, decimals_, domain
  );

  console.log('Result:', result);
}

// ============================================================================
// Circuit: addAdmin
// ============================================================================

/**
 * Call addAdmin circuit
 * @param adminPk - 32-byte value
 * @returns No return value
 */
async function callAddAdmin(
  contractAddress: ContractAddress,
  walletProvider: WalletProvider,
  adminPk: string
): Promise<void> {
  const providers = await initializeProviders();

  try {
    // Create transaction calling addAdmin
    const tx = await createBalancedTx(
      walletProvider,
      providers.privateStateProvider,
      {
        type: 'call-circuit',
        contract: contractAddress,
        circuit: 'addAdmin',
        args: {
          adminPk
        }
      },
      providers.publicDataProvider,
      providers.proofProvider
    );

    // Submit transaction to network
    await providers.nodeProvider.submitTx(tx);

    console.log(`✅ addAdmin transaction submitted`);

    // Wait for transaction confirmation
    const result = await providers.publicDataProvider.waitForTx(tx.txHash);

    console.log(`✅ addAdmin confirmed in block ${result.blockHeight}`);

    return result.output;
  } finally {
    await providers.nodeProvider.close();
  }
}

/**
 * Example usage: addAdmin
 */
async function exampleAddAdmin() {
  const adminPk = 0x0000000000000000000000000000000000000000000000000000000000000000; // Bytes<32>

  // Assuming contract is already deployed
  const contractAddress = 'contract1...'; // Replace with actual address

  // Setup wallet provider (see wallet setup section)
  const walletProvider = await setupWallet();

  const result = await callAddAdmin(
    contractAddress,
    walletProvider,
    adminPk
  );

  console.log('Result:', result);
}

// ============================================================================
// Circuit: removeAdmin
// ============================================================================

/**
 * Call removeAdmin circuit
 * @param adminPk - 32-byte value
 * @returns No return value
 */
async function callRemoveAdmin(
  contractAddress: ContractAddress,
  walletProvider: WalletProvider,
  adminPk: string
): Promise<void> {
  const providers = await initializeProviders();

  try {
    // Create transaction calling removeAdmin
    const tx = await createBalancedTx(
      walletProvider,
      providers.privateStateProvider,
      {
        type: 'call-circuit',
        contract: contractAddress,
        circuit: 'removeAdmin',
        args: {
          adminPk
        }
      },
      providers.publicDataProvider,
      providers.proofProvider
    );

    // Submit transaction to network
    await providers.nodeProvider.submitTx(tx);

    console.log(`✅ removeAdmin transaction submitted`);

    // Wait for transaction confirmation
    const result = await providers.publicDataProvider.waitForTx(tx.txHash);

    console.log(`✅ removeAdmin confirmed in block ${result.blockHeight}`);

    return result.output;
  } finally {
    await providers.nodeProvider.close();
  }
}

/**
 * Example usage: removeAdmin
 */
async function exampleRemoveAdmin() {
  const adminPk = 0x0000000000000000000000000000000000000000000000000000000000000000; // Bytes<32>

  // Assuming contract is already deployed
  const contractAddress = 'contract1...'; // Replace with actual address

  // Setup wallet provider (see wallet setup section)
  const walletProvider = await setupWallet();

  const result = await callRemoveAdmin(
    contractAddress,
    walletProvider,
    adminPk
  );

  console.log('Result:', result);
}

// ============================================================================
// Circuit: pause
// ============================================================================

/**
 * Call pause circuit
 * 
 * @returns No return value
 */
async function callPause(
  contractAddress: ContractAddress,
  walletProvider: WalletProvider,
  
): Promise<void> {
  const providers = await initializeProviders();

  try {
    // Create transaction calling pause
    const tx = await createBalancedTx(
      walletProvider,
      providers.privateStateProvider,
      {
        type: 'call-circuit',
        contract: contractAddress,
        circuit: 'pause',
        args: {}
      },
      providers.publicDataProvider,
      providers.proofProvider
    );

    // Submit transaction to network
    await providers.nodeProvider.submitTx(tx);

    console.log(`✅ pause transaction submitted`);

    // Wait for transaction confirmation
    const result = await providers.publicDataProvider.waitForTx(tx.txHash);

    console.log(`✅ pause confirmed in block ${result.blockHeight}`);

    return result.output;
  } finally {
    await providers.nodeProvider.close();
  }
}

/**
 * Example usage: pause
 */
async function examplePause() {
  // No parameters required

  // Assuming contract is already deployed
  const contractAddress = 'contract1...'; // Replace with actual address

  // Setup wallet provider (see wallet setup section)
  const walletProvider = await setupWallet();

  const result = await callPause(
    contractAddress,
    walletProvider
  );

  console.log('Result:', result);
}

// ============================================================================
// Circuit: unpause
// ============================================================================

/**
 * Call unpause circuit
 * 
 * @returns No return value
 */
async function callUnpause(
  contractAddress: ContractAddress,
  walletProvider: WalletProvider,
  
): Promise<void> {
  const providers = await initializeProviders();

  try {
    // Create transaction calling unpause
    const tx = await createBalancedTx(
      walletProvider,
      providers.privateStateProvider,
      {
        type: 'call-circuit',
        contract: contractAddress,
        circuit: 'unpause',
        args: {}
      },
      providers.publicDataProvider,
      providers.proofProvider
    );

    // Submit transaction to network
    await providers.nodeProvider.submitTx(tx);

    console.log(`✅ unpause transaction submitted`);

    // Wait for transaction confirmation
    const result = await providers.publicDataProvider.waitForTx(tx.txHash);

    console.log(`✅ unpause confirmed in block ${result.blockHeight}`);

    return result.output;
  } finally {
    await providers.nodeProvider.close();
  }
}

/**
 * Example usage: unpause
 */
async function exampleUnpause() {
  // No parameters required

  // Assuming contract is already deployed
  const contractAddress = 'contract1...'; // Replace with actual address

  // Setup wallet provider (see wallet setup section)
  const walletProvider = await setupWallet();

  const result = await callUnpause(
    contractAddress,
    walletProvider
  );

  console.log('Result:', result);
}

// ============================================================================
// Circuit: mintCustodial
// ============================================================================

/**
 * Call mintCustodial circuit
 * @param account - 32-byte value
 * @param amount - Uint<64>
 * @param nonce - 32-byte value
 * @returns No return value
 */
async function callMintCustodial(
  contractAddress: ContractAddress,
  walletProvider: WalletProvider,
  account: string,
  amount: any,
  nonce: string
): Promise<void> {
  const providers = await initializeProviders();

  try {
    // Create transaction calling mintCustodial
    const tx = await createBalancedTx(
      walletProvider,
      providers.privateStateProvider,
      {
        type: 'call-circuit',
        contract: contractAddress,
        circuit: 'mintCustodial',
        args: {
          account,
          amount,
          nonce
        }
      },
      providers.publicDataProvider,
      providers.proofProvider
    );

    // Submit transaction to network
    await providers.nodeProvider.submitTx(tx);

    console.log(`✅ mintCustodial transaction submitted`);

    // Wait for transaction confirmation
    const result = await providers.publicDataProvider.waitForTx(tx.txHash);

    console.log(`✅ mintCustodial confirmed in block ${result.blockHeight}`);

    return result.output;
  } finally {
    await providers.nodeProvider.close();
  }
}

/**
 * Example usage: mintCustodial
 */
async function exampleMintCustodial() {
  const account = 0x0000000000000000000000000000000000000000000000000000000000000000; // Bytes<32>
  const amount = /* TODO: provide value */; // Uint<64>
  const nonce = 0x0000000000000000000000000000000000000000000000000000000000000000; // Bytes<32>

  // Assuming contract is already deployed
  const contractAddress = 'contract1...'; // Replace with actual address

  // Setup wallet provider (see wallet setup section)
  const walletProvider = await setupWallet();

  const result = await callMintCustodial(
    contractAddress,
    walletProvider,
    account, amount, nonce
  );

  console.log('Result:', result);
}

// ============================================================================
// Circuit: mintToHolder
// ============================================================================

/**
 * Call mintToHolder circuit
 * @param recipientKey - ZswapCoinPublicKey
 * @param amount - Uint<64>
 * @param nonce - 32-byte value
 * @returns ShieldedSendResult
 */
async function callMintToHolder(
  contractAddress: ContractAddress,
  walletProvider: WalletProvider,
  recipientKey: any,
  amount: any,
  nonce: string
): Promise<any> {
  const providers = await initializeProviders();

  try {
    // Create transaction calling mintToHolder
    const tx = await createBalancedTx(
      walletProvider,
      providers.privateStateProvider,
      {
        type: 'call-circuit',
        contract: contractAddress,
        circuit: 'mintToHolder',
        args: {
          recipientKey,
          amount,
          nonce
        }
      },
      providers.publicDataProvider,
      providers.proofProvider
    );

    // Submit transaction to network
    await providers.nodeProvider.submitTx(tx);

    console.log(`✅ mintToHolder transaction submitted`);

    // Wait for transaction confirmation
    const result = await providers.publicDataProvider.waitForTx(tx.txHash);

    console.log(`✅ mintToHolder confirmed in block ${result.blockHeight}`);

    return result.output;
  } finally {
    await providers.nodeProvider.close();
  }
}

/**
 * Example usage: mintToHolder
 */
async function exampleMintToHolder() {
  const recipientKey = /* TODO: provide value */; // ZswapCoinPublicKey
  const amount = /* TODO: provide value */; // Uint<64>
  const nonce = 0x0000000000000000000000000000000000000000000000000000000000000000; // Bytes<32>

  // Assuming contract is already deployed
  const contractAddress = 'contract1...'; // Replace with actual address

  // Setup wallet provider (see wallet setup section)
  const walletProvider = await setupWallet();

  const result = await callMintToHolder(
    contractAddress,
    walletProvider,
    recipientKey, amount, nonce
  );

  console.log('Result:', result);
}

// ============================================================================
// Circuit: burnCustodial
// ============================================================================

/**
 * Call burnCustodial circuit
 * @param account - 32-byte value
 * @param amount - Uint<128>
 * @returns No return value
 */
async function callBurnCustodial(
  contractAddress: ContractAddress,
  walletProvider: WalletProvider,
  account: string,
  amount: any
): Promise<void> {
  const providers = await initializeProviders();

  try {
    // Create transaction calling burnCustodial
    const tx = await createBalancedTx(
      walletProvider,
      providers.privateStateProvider,
      {
        type: 'call-circuit',
        contract: contractAddress,
        circuit: 'burnCustodial',
        args: {
          account,
          amount
        }
      },
      providers.publicDataProvider,
      providers.proofProvider
    );

    // Submit transaction to network
    await providers.nodeProvider.submitTx(tx);

    console.log(`✅ burnCustodial transaction submitted`);

    // Wait for transaction confirmation
    const result = await providers.publicDataProvider.waitForTx(tx.txHash);

    console.log(`✅ burnCustodial confirmed in block ${result.blockHeight}`);

    return result.output;
  } finally {
    await providers.nodeProvider.close();
  }
}

/**
 * Example usage: burnCustodial
 */
async function exampleBurnCustodial() {
  const account = 0x0000000000000000000000000000000000000000000000000000000000000000; // Bytes<32>
  const amount = /* TODO: provide value */; // Uint<128>

  // Assuming contract is already deployed
  const contractAddress = 'contract1...'; // Replace with actual address

  // Setup wallet provider (see wallet setup section)
  const walletProvider = await setupWallet();

  const result = await callBurnCustodial(
    contractAddress,
    walletProvider,
    account, amount
  );

  console.log('Result:', result);
}

// ============================================================================
// Circuit: custodialTransfer
// ============================================================================

/**
 * Call custodialTransfer circuit
 * @param sender - 32-byte value
 * @param receiver - 32-byte value
 * @param amount - Uint<128>
 * @returns No return value
 */
async function callCustodialTransfer(
  contractAddress: ContractAddress,
  walletProvider: WalletProvider,
  sender: string,
  receiver: string,
  amount: any
): Promise<void> {
  const providers = await initializeProviders();

  try {
    // Create transaction calling custodialTransfer
    const tx = await createBalancedTx(
      walletProvider,
      providers.privateStateProvider,
      {
        type: 'call-circuit',
        contract: contractAddress,
        circuit: 'custodialTransfer',
        args: {
          sender,
          receiver,
          amount
        }
      },
      providers.publicDataProvider,
      providers.proofProvider
    );

    // Submit transaction to network
    await providers.nodeProvider.submitTx(tx);

    console.log(`✅ custodialTransfer transaction submitted`);

    // Wait for transaction confirmation
    const result = await providers.publicDataProvider.waitForTx(tx.txHash);

    console.log(`✅ custodialTransfer confirmed in block ${result.blockHeight}`);

    return result.output;
  } finally {
    await providers.nodeProvider.close();
  }
}

/**
 * Example usage: custodialTransfer
 */
async function exampleCustodialTransfer() {
  const sender = 0x0000000000000000000000000000000000000000000000000000000000000000; // Bytes<32>
  const receiver = 0x0000000000000000000000000000000000000000000000000000000000000000; // Bytes<32>
  const amount = /* TODO: provide value */; // Uint<128>

  // Assuming contract is already deployed
  const contractAddress = 'contract1...'; // Replace with actual address

  // Setup wallet provider (see wallet setup section)
  const walletProvider = await setupWallet();

  const result = await callCustodialTransfer(
    contractAddress,
    walletProvider,
    sender, receiver, amount
  );

  console.log('Result:', result);
}

// ============================================================================
// Circuit: freeze
// ============================================================================

/**
 * Call freeze circuit
 * @param account - 32-byte value
 * @returns No return value
 */
async function callFreeze(
  contractAddress: ContractAddress,
  walletProvider: WalletProvider,
  account: string
): Promise<void> {
  const providers = await initializeProviders();

  try {
    // Create transaction calling freeze
    const tx = await createBalancedTx(
      walletProvider,
      providers.privateStateProvider,
      {
        type: 'call-circuit',
        contract: contractAddress,
        circuit: 'freeze',
        args: {
          account
        }
      },
      providers.publicDataProvider,
      providers.proofProvider
    );

    // Submit transaction to network
    await providers.nodeProvider.submitTx(tx);

    console.log(`✅ freeze transaction submitted`);

    // Wait for transaction confirmation
    const result = await providers.publicDataProvider.waitForTx(tx.txHash);

    console.log(`✅ freeze confirmed in block ${result.blockHeight}`);

    return result.output;
  } finally {
    await providers.nodeProvider.close();
  }
}

/**
 * Example usage: freeze
 */
async function exampleFreeze() {
  const account = 0x0000000000000000000000000000000000000000000000000000000000000000; // Bytes<32>

  // Assuming contract is already deployed
  const contractAddress = 'contract1...'; // Replace with actual address

  // Setup wallet provider (see wallet setup section)
  const walletProvider = await setupWallet();

  const result = await callFreeze(
    contractAddress,
    walletProvider,
    account
  );

  console.log('Result:', result);
}

// ============================================================================
// Circuit: unfreeze
// ============================================================================

/**
 * Call unfreeze circuit
 * @param account - 32-byte value
 * @returns No return value
 */
async function callUnfreeze(
  contractAddress: ContractAddress,
  walletProvider: WalletProvider,
  account: string
): Promise<void> {
  const providers = await initializeProviders();

  try {
    // Create transaction calling unfreeze
    const tx = await createBalancedTx(
      walletProvider,
      providers.privateStateProvider,
      {
        type: 'call-circuit',
        contract: contractAddress,
        circuit: 'unfreeze',
        args: {
          account
        }
      },
      providers.publicDataProvider,
      providers.proofProvider
    );

    // Submit transaction to network
    await providers.nodeProvider.submitTx(tx);

    console.log(`✅ unfreeze transaction submitted`);

    // Wait for transaction confirmation
    const result = await providers.publicDataProvider.waitForTx(tx.txHash);

    console.log(`✅ unfreeze confirmed in block ${result.blockHeight}`);

    return result.output;
  } finally {
    await providers.nodeProvider.close();
  }
}

/**
 * Example usage: unfreeze
 */
async function exampleUnfreeze() {
  const account = 0x0000000000000000000000000000000000000000000000000000000000000000; // Bytes<32>

  // Assuming contract is already deployed
  const contractAddress = 'contract1...'; // Replace with actual address

  // Setup wallet provider (see wallet setup section)
  const walletProvider = await setupWallet();

  const result = await callUnfreeze(
    contractAddress,
    walletProvider,
    account
  );

  console.log('Result:', result);
}

// ============================================================================
// Circuit: forceTransfer
// ============================================================================

/**
 * Call forceTransfer circuit
 * @param sender - 32-byte value
 * @param receiver - 32-byte value
 * @param amount - Uint<128>
 * @returns No return value
 */
async function callForceTransfer(
  contractAddress: ContractAddress,
  walletProvider: WalletProvider,
  sender: string,
  receiver: string,
  amount: any
): Promise<void> {
  const providers = await initializeProviders();

  try {
    // Create transaction calling forceTransfer
    const tx = await createBalancedTx(
      walletProvider,
      providers.privateStateProvider,
      {
        type: 'call-circuit',
        contract: contractAddress,
        circuit: 'forceTransfer',
        args: {
          sender,
          receiver,
          amount
        }
      },
      providers.publicDataProvider,
      providers.proofProvider
    );

    // Submit transaction to network
    await providers.nodeProvider.submitTx(tx);

    console.log(`✅ forceTransfer transaction submitted`);

    // Wait for transaction confirmation
    const result = await providers.publicDataProvider.waitForTx(tx.txHash);

    console.log(`✅ forceTransfer confirmed in block ${result.blockHeight}`);

    return result.output;
  } finally {
    await providers.nodeProvider.close();
  }
}

/**
 * Example usage: forceTransfer
 */
async function exampleForceTransfer() {
  const sender = 0x0000000000000000000000000000000000000000000000000000000000000000; // Bytes<32>
  const receiver = 0x0000000000000000000000000000000000000000000000000000000000000000; // Bytes<32>
  const amount = /* TODO: provide value */; // Uint<128>

  // Assuming contract is already deployed
  const contractAddress = 'contract1...'; // Replace with actual address

  // Setup wallet provider (see wallet setup section)
  const walletProvider = await setupWallet();

  const result = await callForceTransfer(
    contractAddress,
    walletProvider,
    sender, receiver, amount
  );

  console.log('Result:', result);
}

// ============================================================================
// Circuit: addToAllowlist
// ============================================================================

/**
 * Call addToAllowlist circuit
 * @param account - 32-byte value
 * @returns No return value
 */
async function callAddToAllowlist(
  contractAddress: ContractAddress,
  walletProvider: WalletProvider,
  account: string
): Promise<void> {
  const providers = await initializeProviders();

  try {
    // Create transaction calling addToAllowlist
    const tx = await createBalancedTx(
      walletProvider,
      providers.privateStateProvider,
      {
        type: 'call-circuit',
        contract: contractAddress,
        circuit: 'addToAllowlist',
        args: {
          account
        }
      },
      providers.publicDataProvider,
      providers.proofProvider
    );

    // Submit transaction to network
    await providers.nodeProvider.submitTx(tx);

    console.log(`✅ addToAllowlist transaction submitted`);

    // Wait for transaction confirmation
    const result = await providers.publicDataProvider.waitForTx(tx.txHash);

    console.log(`✅ addToAllowlist confirmed in block ${result.blockHeight}`);

    return result.output;
  } finally {
    await providers.nodeProvider.close();
  }
}

/**
 * Example usage: addToAllowlist
 */
async function exampleAddToAllowlist() {
  const account = 0x0000000000000000000000000000000000000000000000000000000000000000; // Bytes<32>

  // Assuming contract is already deployed
  const contractAddress = 'contract1...'; // Replace with actual address

  // Setup wallet provider (see wallet setup section)
  const walletProvider = await setupWallet();

  const result = await callAddToAllowlist(
    contractAddress,
    walletProvider,
    account
  );

  console.log('Result:', result);
}

// ============================================================================
// Circuit: removeFromAllowlist
// ============================================================================

/**
 * Call removeFromAllowlist circuit
 * @param account - 32-byte value
 * @returns No return value
 */
async function callRemoveFromAllowlist(
  contractAddress: ContractAddress,
  walletProvider: WalletProvider,
  account: string
): Promise<void> {
  const providers = await initializeProviders();

  try {
    // Create transaction calling removeFromAllowlist
    const tx = await createBalancedTx(
      walletProvider,
      providers.privateStateProvider,
      {
        type: 'call-circuit',
        contract: contractAddress,
        circuit: 'removeFromAllowlist',
        args: {
          account
        }
      },
      providers.publicDataProvider,
      providers.proofProvider
    );

    // Submit transaction to network
    await providers.nodeProvider.submitTx(tx);

    console.log(`✅ removeFromAllowlist transaction submitted`);

    // Wait for transaction confirmation
    const result = await providers.publicDataProvider.waitForTx(tx.txHash);

    console.log(`✅ removeFromAllowlist confirmed in block ${result.blockHeight}`);

    return result.output;
  } finally {
    await providers.nodeProvider.close();
  }
}

/**
 * Example usage: removeFromAllowlist
 */
async function exampleRemoveFromAllowlist() {
  const account = 0x0000000000000000000000000000000000000000000000000000000000000000; // Bytes<32>

  // Assuming contract is already deployed
  const contractAddress = 'contract1...'; // Replace with actual address

  // Setup wallet provider (see wallet setup section)
  const walletProvider = await setupWallet();

  const result = await callRemoveFromAllowlist(
    contractAddress,
    walletProvider,
    account
  );

  console.log('Result:', result);
}

// ============================================================================
// Circuit: updatePolicy
// ============================================================================

/**
 * Call updatePolicy circuit
 * @param newMaxMint - Uint<128>
 * @param newMaxTransfer - Uint<128>
 * @param newUseAllowlist - Boolean value
 * @returns No return value
 */
async function callUpdatePolicy(
  contractAddress: ContractAddress,
  walletProvider: WalletProvider,
  newMaxMint: any,
  newMaxTransfer: any,
  newUseAllowlist: boolean
): Promise<void> {
  const providers = await initializeProviders();

  try {
    // Create transaction calling updatePolicy
    const tx = await createBalancedTx(
      walletProvider,
      providers.privateStateProvider,
      {
        type: 'call-circuit',
        contract: contractAddress,
        circuit: 'updatePolicy',
        args: {
          newMaxMint,
          newMaxTransfer,
          newUseAllowlist
        }
      },
      providers.publicDataProvider,
      providers.proofProvider
    );

    // Submit transaction to network
    await providers.nodeProvider.submitTx(tx);

    console.log(`✅ updatePolicy transaction submitted`);

    // Wait for transaction confirmation
    const result = await providers.publicDataProvider.waitForTx(tx.txHash);

    console.log(`✅ updatePolicy confirmed in block ${result.blockHeight}`);

    return result.output;
  } finally {
    await providers.nodeProvider.close();
  }
}

/**
 * Example usage: updatePolicy
 */
async function exampleUpdatePolicy() {
  const newMaxMint = /* TODO: provide value */; // Uint<128>
  const newMaxTransfer = /* TODO: provide value */; // Uint<128>
  const newUseAllowlist = true; // Boolean

  // Assuming contract is already deployed
  const contractAddress = 'contract1...'; // Replace with actual address

  // Setup wallet provider (see wallet setup section)
  const walletProvider = await setupWallet();

  const result = await callUpdatePolicy(
    contractAddress,
    walletProvider,
    newMaxMint, newMaxTransfer, newUseAllowlist
  );

  console.log('Result:', result);
}

// ============================================================================
// Circuit: prepareWithdraw
// ============================================================================

/**
 * Call prepareWithdraw circuit
 * @param account - 32-byte value
 * @param withdrawValue - Uint<64>
 * @returns 32-byte value
 */
async function callPrepareWithdraw(
  contractAddress: ContractAddress,
  walletProvider: WalletProvider,
  account: string,
  withdrawValue: any
): Promise<string> {
  const providers = await initializeProviders();

  try {
    // Create transaction calling prepareWithdraw
    const tx = await createBalancedTx(
      walletProvider,
      providers.privateStateProvider,
      {
        type: 'call-circuit',
        contract: contractAddress,
        circuit: 'prepareWithdraw',
        args: {
          account,
          withdrawValue
        }
      },
      providers.publicDataProvider,
      providers.proofProvider
    );

    // Submit transaction to network
    await providers.nodeProvider.submitTx(tx);

    console.log(`✅ prepareWithdraw transaction submitted`);

    // Wait for transaction confirmation
    const result = await providers.publicDataProvider.waitForTx(tx.txHash);

    console.log(`✅ prepareWithdraw confirmed in block ${result.blockHeight}`);

    return result.output;
  } finally {
    await providers.nodeProvider.close();
  }
}

/**
 * Example usage: prepareWithdraw
 */
async function examplePrepareWithdraw() {
  const account = 0x0000000000000000000000000000000000000000000000000000000000000000; // Bytes<32>
  const withdrawValue = /* TODO: provide value */; // Uint<64>

  // Assuming contract is already deployed
  const contractAddress = 'contract1...'; // Replace with actual address

  // Setup wallet provider (see wallet setup section)
  const walletProvider = await setupWallet();

  const result = await callPrepareWithdraw(
    contractAddress,
    walletProvider,
    account, withdrawValue
  );

  console.log('Result:', result);
}

// ============================================================================
// Circuit: executeWithdraw
// ============================================================================

/**
 * Call executeWithdraw circuit
 * @param recipient - UserAddress
 * @param withdrawValue - Uint<64>
 * @returns No return value
 */
async function callExecuteWithdraw(
  contractAddress: ContractAddress,
  walletProvider: WalletProvider,
  recipient: any,
  withdrawValue: any
): Promise<void> {
  const providers = await initializeProviders();

  try {
    // Create transaction calling executeWithdraw
    const tx = await createBalancedTx(
      walletProvider,
      providers.privateStateProvider,
      {
        type: 'call-circuit',
        contract: contractAddress,
        circuit: 'executeWithdraw',
        args: {
          recipient,
          withdrawValue
        }
      },
      providers.publicDataProvider,
      providers.proofProvider
    );

    // Submit transaction to network
    await providers.nodeProvider.submitTx(tx);

    console.log(`✅ executeWithdraw transaction submitted`);

    // Wait for transaction confirmation
    const result = await providers.publicDataProvider.waitForTx(tx.txHash);

    console.log(`✅ executeWithdraw confirmed in block ${result.blockHeight}`);

    return result.output;
  } finally {
    await providers.nodeProvider.close();
  }
}

/**
 * Example usage: executeWithdraw
 */
async function exampleExecuteWithdraw() {
  const recipient = /* TODO: provide value */; // UserAddress
  const withdrawValue = /* TODO: provide value */; // Uint<64>

  // Assuming contract is already deployed
  const contractAddress = 'contract1...'; // Replace with actual address

  // Setup wallet provider (see wallet setup section)
  const walletProvider = await setupWallet();

  const result = await callExecuteWithdraw(
    contractAddress,
    walletProvider,
    recipient, withdrawValue
  );

  console.log('Result:', result);
}

// ============================================================================
// Circuit: mergeTwoCoins
// ============================================================================

/**
 * Call mergeTwoCoins circuit
 * @param coin1 - QualifiedShieldedCoinInfo
 * @param coin2 - QualifiedShieldedCoinInfo
 * @param callerKey - ZswapCoinPublicKey
 * @returns ShieldedCoinInfo
 */
async function callMergeTwoCoins(
  contractAddress: ContractAddress,
  walletProvider: WalletProvider,
  coin1: any,
  coin2: any,
  callerKey: any
): Promise<any> {
  const providers = await initializeProviders();

  try {
    // Create transaction calling mergeTwoCoins
    const tx = await createBalancedTx(
      walletProvider,
      providers.privateStateProvider,
      {
        type: 'call-circuit',
        contract: contractAddress,
        circuit: 'mergeTwoCoins',
        args: {
          coin1,
          coin2,
          callerKey
        }
      },
      providers.publicDataProvider,
      providers.proofProvider
    );

    // Submit transaction to network
    await providers.nodeProvider.submitTx(tx);

    console.log(`✅ mergeTwoCoins transaction submitted`);

    // Wait for transaction confirmation
    const result = await providers.publicDataProvider.waitForTx(tx.txHash);

    console.log(`✅ mergeTwoCoins confirmed in block ${result.blockHeight}`);

    return result.output;
  } finally {
    await providers.nodeProvider.close();
  }
}

/**
 * Example usage: mergeTwoCoins
 */
async function exampleMergeTwoCoins() {
  const coin1 = /* TODO: provide value */; // QualifiedShieldedCoinInfo
  const coin2 = /* TODO: provide value */; // QualifiedShieldedCoinInfo
  const callerKey = /* TODO: provide value */; // ZswapCoinPublicKey

  // Assuming contract is already deployed
  const contractAddress = 'contract1...'; // Replace with actual address

  // Setup wallet provider (see wallet setup section)
  const walletProvider = await setupWallet();

  const result = await callMergeTwoCoins(
    contractAddress,
    walletProvider,
    coin1, coin2, callerKey
  );

  console.log('Result:', result);
}

// ============================================================================
// Circuit: mergeWithImmediate
// ============================================================================

/**
 * Call mergeWithImmediate circuit
 * @param confirmed - QualifiedShieldedCoinInfo
 * @param immediate - ShieldedCoinInfo
 * @param callerKey - ZswapCoinPublicKey
 * @returns ShieldedCoinInfo
 */
async function callMergeWithImmediate(
  contractAddress: ContractAddress,
  walletProvider: WalletProvider,
  confirmed: any,
  immediate: any,
  callerKey: any
): Promise<any> {
  const providers = await initializeProviders();

  try {
    // Create transaction calling mergeWithImmediate
    const tx = await createBalancedTx(
      walletProvider,
      providers.privateStateProvider,
      {
        type: 'call-circuit',
        contract: contractAddress,
        circuit: 'mergeWithImmediate',
        args: {
          confirmed,
          immediate,
          callerKey
        }
      },
      providers.publicDataProvider,
      providers.proofProvider
    );

    // Submit transaction to network
    await providers.nodeProvider.submitTx(tx);

    console.log(`✅ mergeWithImmediate transaction submitted`);

    // Wait for transaction confirmation
    const result = await providers.publicDataProvider.waitForTx(tx.txHash);

    console.log(`✅ mergeWithImmediate confirmed in block ${result.blockHeight}`);

    return result.output;
  } finally {
    await providers.nodeProvider.close();
  }
}

/**
 * Example usage: mergeWithImmediate
 */
async function exampleMergeWithImmediate() {
  const confirmed = /* TODO: provide value */; // QualifiedShieldedCoinInfo
  const immediate = /* TODO: provide value */; // ShieldedCoinInfo
  const callerKey = /* TODO: provide value */; // ZswapCoinPublicKey

  // Assuming contract is already deployed
  const contractAddress = 'contract1...'; // Replace with actual address

  // Setup wallet provider (see wallet setup section)
  const walletProvider = await setupWallet();

  const result = await callMergeWithImmediate(
    contractAddress,
    walletProvider,
    confirmed, immediate, callerKey
  );

  console.log('Result:', result);
}

// ============================================================================
// Circuit: shieldedTransfer
// ============================================================================

/**
 * Call shieldedTransfer circuit
 * @param input - QualifiedShieldedCoinInfo
 * @param recipientKey - ZswapCoinPublicKey
 * @param value - Uint<128>
 * @returns ShieldedSendResult
 */
async function callShieldedTransfer(
  contractAddress: ContractAddress,
  walletProvider: WalletProvider,
  input: any,
  recipientKey: any,
  value: any
): Promise<any> {
  const providers = await initializeProviders();

  try {
    // Create transaction calling shieldedTransfer
    const tx = await createBalancedTx(
      walletProvider,
      providers.privateStateProvider,
      {
        type: 'call-circuit',
        contract: contractAddress,
        circuit: 'shieldedTransfer',
        args: {
          input,
          recipientKey,
          value
        }
      },
      providers.publicDataProvider,
      providers.proofProvider
    );

    // Submit transaction to network
    await providers.nodeProvider.submitTx(tx);

    console.log(`✅ shieldedTransfer transaction submitted`);

    // Wait for transaction confirmation
    const result = await providers.publicDataProvider.waitForTx(tx.txHash);

    console.log(`✅ shieldedTransfer confirmed in block ${result.blockHeight}`);

    return result.output;
  } finally {
    await providers.nodeProvider.close();
  }
}

/**
 * Example usage: shieldedTransfer
 */
async function exampleShieldedTransfer() {
  const input = /* TODO: provide value */; // QualifiedShieldedCoinInfo
  const recipientKey = /* TODO: provide value */; // ZswapCoinPublicKey
  const value = /* TODO: provide value */; // Uint<128>

  // Assuming contract is already deployed
  const contractAddress = 'contract1...'; // Replace with actual address

  // Setup wallet provider (see wallet setup section)
  const walletProvider = await setupWallet();

  const result = await callShieldedTransfer(
    contractAddress,
    walletProvider,
    input, recipientKey, value
  );

  console.log('Result:', result);
}

// ============================================================================
// Circuit: shieldedTransferToContract
// ============================================================================

/**
 * Call shieldedTransferToContract circuit
 * @param input - QualifiedShieldedCoinInfo
 * @param recipient - ContractAddress
 * @param value - Uint<128>
 * @returns ShieldedSendResult
 */
async function callShieldedTransferToContract(
  contractAddress: ContractAddress,
  walletProvider: WalletProvider,
  input: any,
  recipient: any,
  value: any
): Promise<any> {
  const providers = await initializeProviders();

  try {
    // Create transaction calling shieldedTransferToContract
    const tx = await createBalancedTx(
      walletProvider,
      providers.privateStateProvider,
      {
        type: 'call-circuit',
        contract: contractAddress,
        circuit: 'shieldedTransferToContract',
        args: {
          input,
          recipient,
          value
        }
      },
      providers.publicDataProvider,
      providers.proofProvider
    );

    // Submit transaction to network
    await providers.nodeProvider.submitTx(tx);

    console.log(`✅ shieldedTransferToContract transaction submitted`);

    // Wait for transaction confirmation
    const result = await providers.publicDataProvider.waitForTx(tx.txHash);

    console.log(`✅ shieldedTransferToContract confirmed in block ${result.blockHeight}`);

    return result.output;
  } finally {
    await providers.nodeProvider.close();
  }
}

/**
 * Example usage: shieldedTransferToContract
 */
async function exampleShieldedTransferToContract() {
  const input = /* TODO: provide value */; // QualifiedShieldedCoinInfo
  const recipient = /* TODO: provide value */; // ContractAddress
  const value = /* TODO: provide value */; // Uint<128>

  // Assuming contract is already deployed
  const contractAddress = 'contract1...'; // Replace with actual address

  // Setup wallet provider (see wallet setup section)
  const walletProvider = await setupWallet();

  const result = await callShieldedTransferToContract(
    contractAddress,
    walletProvider,
    input, recipient, value
  );

  console.log('Result:', result);
}

// ============================================================================
// Complete Workflow Example
// ============================================================================

/**
 * Complete example: Deploy contract and execute circuits
 */
async function completeWorkflow() {
  console.log('🚀 Starting compliant-token-full workflow...\n');

  // 1. Initialize providers
  console.log('1️⃣  Initializing providers...');
  const providers = await initializeProviders();

  // 2. Setup wallet
  console.log('2️⃣  Setting up wallet...');
  const walletProvider = await setupWallet();

  try {
    // 3. Deploy contract
    console.log('3️⃣  Deploying contract...');
    const deployTx = await deployContract(
      walletProvider,
      providers.privateStateProvider,
      contract,
      {}, // Initial state
      providers.publicDataProvider,
      providers.proofProvider
    );

    await providers.nodeProvider.submitTx(deployTx);
    const deployResult = await providers.publicDataProvider.waitForTx(deployTx.txHash);
    const contractAddress = deployResult.contractAddress;

    console.log(`✅ Contract deployed at: ${contractAddress}\n`);

    // 4. Execute circuits
    console.log('4️⃣  Calling initializeToken...');
    await callInitializeToken(contractAddress, walletProvider, /* param */, /* param */, /* param */, /* param */);
    console.log('');

    console.log('5️⃣  Calling addAdmin...');
    await callAddAdmin(contractAddress, walletProvider, /* param */);
    console.log('');

    console.log('6️⃣  Calling removeAdmin...');
    await callRemoveAdmin(contractAddress, walletProvider, /* param */);
    console.log('');

    console.log('✨ Workflow completed successfully!');

  } catch (error) {
    console.error('❌ Workflow failed:', error);
    throw error;
  } finally {
    await providers.nodeProvider.close();
  }
}

// ============================================================================
// Error Handling
// ============================================================================

/**
 * Robust circuit call with error handling
 */
async function callCircuitWithErrorHandling(
  circuit: string,
  args: any
): Promise<any> {
  const providers = await initializeProviders();

  try {
    // Attempt circuit call with retry logic
    const maxRetries = 3;
    let lastError: Error | null = null;

    for (let attempt = 1; attempt <= maxRetries; attempt++) {
      try {
        const tx = await createBalancedTx(
          walletProvider,
          providers.privateStateProvider,
          { type: 'call-circuit', circuit, args },
          providers.publicDataProvider,
          providers.proofProvider
        );

        await providers.nodeProvider.submitTx(tx);
        const result = await providers.publicDataProvider.waitForTx(tx.txHash);

        return result.output;

      } catch (error) {
        lastError = error as Error;
        console.warn(`Attempt ${attempt}/${maxRetries} failed: ${error.message}`);

        if (attempt < maxRetries) {
          // Exponential backoff
          await new Promise(resolve => setTimeout(resolve, 1000 * Math.pow(2, attempt)));
        }
      }
    }

    throw new Error(`Circuit call failed after ${maxRetries} attempts: ${lastError?.message}`);

  } catch (error) {
    if (error.message.includes('insufficient funds')) {
      console.error('❌ Insufficient DUST balance');
    } else if (error.message.includes('assertion failed')) {
      console.error('❌ Circuit assertion failed - check preconditions');
    } else if (error.message.includes('timeout')) {
      console.error('❌ Proof generation timeout - circuit may be too complex');
    } else {
      console.error('❌ Unexpected error:', error);
    }

    throw error;
  } finally {
    await providers.nodeProvider.close();
  }
}

// ============================================================================
// Testing
// ============================================================================

/**
 * Unit test example using Jest
 */
describe('compliant-token-full Contract', () => {
  let contractAddress: ContractAddress;
  let walletProvider: WalletProvider;
  let providers: Awaited<ReturnType<typeof initializeProviders>>;

  beforeAll(async () => {
    providers = await initializeProviders();
    walletProvider = await setupWallet();

    // Deploy contract for testing
    const deployTx = await deployContract(
      walletProvider,
      providers.privateStateProvider,
      contract,
      {},
      providers.publicDataProvider,
      providers.proofProvider
    );

    await providers.nodeProvider.submitTx(deployTx);
    const result = await providers.publicDataProvider.waitForTx(deployTx.txHash);
    contractAddress = result.contractAddress;
  });

  afterAll(async () => {
    await providers.nodeProvider.close();
  });

  test('should call initializeToken successfully', async () => {
    const name_ = "example"; // Opaque<"string">
  const symbol_ = "example"; // Opaque<"string">
  const decimals_ = /* TODO: provide value */; // Uint<8>
  const domain = 0x0000000000000000000000000000000000000000000000000000000000000000; // Bytes<32>

    const result = await callInitializeToken(
      contractAddress,
      walletProvider,
      name_,
      symbol_,
      decimals_,
      domain
    );

    expect(result).toBeDefined();
    // Add more assertions based on expected behavior
  });

  test('should fail with invalid parameters', async () => {
    await expect(
      callInitializeToken(
        contractAddress,
        walletProvider,
        null as any,
        null as any,
        null as any,
        null as any
      )
    ).rejects.toThrow();
  });
});

// ============================================================================
// Utility Functions
// ============================================================================

/**
 * Setup wallet provider
 * Replace with actual wallet initialization
 */
async function setupWallet(): Promise<WalletProvider> {
  // TODO: Initialize wallet with seed phrase or private key
  throw new Error('Wallet setup not implemented');
}

// ============================================================================
// Run Examples
// ============================================================================

// Uncomment to run specific examples:
// exampleInitializeToken().catch(console.error);
// completeWorkflow().catch(console.error);
