/**
 * Integration Examples Generator
 *
 * Generates TypeScript/JavaScript usage examples for circuits
 */

import { readFileSync, existsSync } from 'fs';
import { basename } from 'path';
import type { AnalysisResult } from './types.js';

interface CircuitInfo {
  name: string;
  params: Array<{ name: string; type: string }>;
  returnType: string;
  isExported: boolean;
}

export class IntegrationExamplesGenerator {
  private contractSource: string;
  private contractPath: string;
  private result: AnalysisResult;
  private contractName: string;

  constructor(contractPath: string, result: AnalysisResult) {
    if (!existsSync(contractPath)) {
      throw new Error(`Contract file not found: ${contractPath}`);
    }

    this.contractSource = readFileSync(contractPath, 'utf8');
    this.contractPath = contractPath;
    this.result = result;
    this.contractName = basename(contractPath, '.compact');
  }

  /**
   * Generate complete integration examples
   */
  public generate(): string {
    const circuits = this.parseCircuits();
    const exportedCircuits = circuits.filter(c => c.isExported);

    if (exportedCircuits.length === 0) {
      return '// No exported circuits found';
    }

    let examples = this.generateHeader();
    examples += this.generateSetupExample();
    examples += this.generateProviderSetup();

    for (const circuit of exportedCircuits) {
      examples += this.generateCircuitExample(circuit);
    }

    examples += this.generateFullWorkflowExample(exportedCircuits);
    examples += this.generateErrorHandlingExample();
    examples += this.generateTestingExample(exportedCircuits[0]);

    return examples;
  }

  /**
   * Parse circuit information
   */
  private parseCircuits(): CircuitInfo[] {
    const circuits: CircuitInfo[] = [];
    const circuitRegex = /(export\s+)?circuit\s+(\w+)\s*\(([^)]*)\)\s*:\s*([^{]+)/g;
    let match;

    while ((match = circuitRegex.exec(this.contractSource)) !== null) {
      const isExported = !!match[1];
      const name = match[2];
      const paramsStr = match[3];
      const returnType = match[4].trim();

      const params: Array<{ name: string; type: string }> = [];
      if (paramsStr.trim()) {
        const paramPairs = paramsStr.split(',');
        for (const pair of paramPairs) {
          const colonIndex = pair.indexOf(':');
          if (colonIndex !== -1) {
            params.push({
              name: pair.substring(0, colonIndex).trim(),
              type: pair.substring(colonIndex + 1).trim()
            });
          }
        }
      }

      circuits.push({ name, params, returnType, isExported });
    }

    return circuits;
  }

  /**
   * Generate file header
   */
  private generateHeader(): string {
    return `/**
 * ${this.contractName} Contract Integration Examples
 *
 * Generated by Compact Circuit Analyzer
 * Generated: ${new Date(this.result.timestamp).toLocaleString()}
 * Compiler: ${this.result.compilerVersion || 'Unknown'}
 *
 * These examples show how to interact with the ${this.contractName} contract
 * using the Midnight.js SDK.
 */

import {
  createBalancedTx,
  type Contract,
  type ContractAddress,
  deployContract,
  findDeployedContract,
  providers
} from '@midnight-ntwrk/midnight-js-contracts';
import {
  type PrivateStateProvider,
  type PublicDataProvider,
  type ProofProvider,
  type WalletProvider
} from '@midnight-ntwrk/midnight-js-types';
import { NodeProvider } from '@midnight-ntwrk/midnight-js-node-provider';
import { IndexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { HttpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { LevelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';

// Import generated contract artifacts
import contract from './${this.contractName}';

`;
  }

  /**
   * Generate setup example
   */
  private generateSetupExample(): string {
    return `// ============================================================================
// Setup and Configuration
// ============================================================================

/**
 * Network configuration
 */
const NETWORK_CONFIG = {
  // Local development node
  local: {
    nodeUrl: 'ws://localhost:9944',
    indexerUrl: 'http://localhost:8088/graphql',
    proofServerUrl: 'http://localhost:6300'
  },
  // QANet test network
  qanet: {
    nodeUrl: 'wss://qanet-node.midnight.network',
    indexerUrl: 'https://qanet-indexer.midnight.network/graphql',
    proofServerUrl: 'https://qanet-proof-server.midnight.network'
  }
};

// Select network (change as needed)
const network = NETWORK_CONFIG.local;

`;
  }

  /**
   * Generate provider setup
   */
  private generateProviderSetup(): string {
    return `/**
 * Initialize Midnight.js providers
 */
async function initializeProviders(): Promise<{
  nodeProvider: NodeProvider;
  publicDataProvider: PublicDataProvider;
  privateStateProvider: PrivateStateProvider;
  proofProvider: ProofProvider;
}> {
  // Connect to Midnight node
  const nodeProvider = await NodeProvider.create(network.nodeUrl);

  // Setup public data provider (indexer)
  const publicDataProvider = new IndexerPublicDataProvider(
    network.indexerUrl,
    { timeout: 30000 }
  );

  // Setup private state storage (using LevelDB)
  const privateStateProvider = new LevelPrivateStateProvider({
    storePath: './.midnight-private-state'
  });

  // Setup proof server connection
  const proofProvider = new HttpClientProofProvider(
    network.proofServerUrl,
    { timeout: 120000 } // Proving can take time
  );

  return {
    nodeProvider,
    publicDataProvider,
    privateStateProvider,
    proofProvider
  };
}

`;
  }

  /**
   * Generate example for a specific circuit
   */
  private generateCircuitExample(circuit: CircuitInfo): string {
    const paramExamples = this.generateParamExamples(circuit.params);
    const paramList = circuit.params.map(p => p.name).join(', ');

    return `// ============================================================================
// Circuit: ${circuit.name}
// ============================================================================

/**
 * Call ${circuit.name} circuit
 * ${circuit.params.length > 0 ? `@param ${circuit.params.map(p => `${p.name} - ${this.getTypeDescription(p.type)}`).join('\n * @param ')}` : ''}
 * @returns ${this.getTypeDescription(circuit.returnType)}
 */
async function call${this.capitalize(circuit.name)}(
  contractAddress: ContractAddress,
  walletProvider: WalletProvider,
  ${circuit.params.map(p => `${p.name}: ${this.mapCompactTypeToTS(p.type)}`).join(',\n  ')}
): Promise<${this.mapCompactTypeToTS(circuit.returnType)}> {
  const providers = await initializeProviders();

  try {
    // Create transaction calling ${circuit.name}
    const tx = await createBalancedTx(
      walletProvider,
      providers.privateStateProvider,
      {
        type: 'call-circuit',
        contract: contractAddress,
        circuit: '${circuit.name}',
        args: {${paramList ? `\n          ${circuit.params.map(p => `${p.name}`).join(',\n          ')}\n        ` : ''}}
      },
      providers.publicDataProvider,
      providers.proofProvider
    );

    // Submit transaction to network
    await providers.nodeProvider.submitTx(tx);

    console.log(\`✅ ${circuit.name} transaction submitted\`);

    // Wait for transaction confirmation
    const result = await providers.publicDataProvider.waitForTx(tx.txHash);

    console.log(\`✅ ${circuit.name} confirmed in block \${result.blockHeight}\`);

    return result.output;
  } finally {
    await providers.nodeProvider.close();
  }
}

/**
 * Example usage: ${circuit.name}
 */
async function example${this.capitalize(circuit.name)}() {
  ${paramExamples}

  // Assuming contract is already deployed
  const contractAddress = 'contract1...'; // Replace with actual address

  // Setup wallet provider (see wallet setup section)
  const walletProvider = await setupWallet();

  const result = await call${this.capitalize(circuit.name)}(
    contractAddress,
    walletProvider${paramList ? `,\n    ${paramList}` : ''}
  );

  console.log('Result:', result);
}

`;
  }

  /**
   * Generate parameter examples
   */
  private generateParamExamples(params: Array<{ name: string; type: string }>): string {
    if (params.length === 0) {
      return '// No parameters required';
    }

    return params.map(p => {
      const example = this.generateTypeExample(p.type);
      return `const ${p.name} = ${example}; // ${p.type}`;
    }).join('\n  ');
  }

  /**
   * Generate example value for a type
   */
  private generateTypeExample(type: string): string {
    // Handle common Compact types
    if (type.includes('Field')) return '0n';
    if (type.includes('Bytes<32>')) return '0x' + '0'.repeat(64);
    if (type.includes('Bytes<')) return '0x' + '0'.repeat(32);
    if (type.includes('Opaque<"string">')) return '"example"';
    if (type.includes('Boolean')) return 'true';
    if (type.includes('Maybe<')) return '{ is_some: true, value: ... }';
    if (type.includes('[]')) return '[]';
    if (type === '[]') return 'undefined';

    return '/* TODO: provide value */';
  }

  /**
   * Map Compact type to TypeScript type
   */
  private mapCompactTypeToTS(type: string): string {
    if (type === '[]') return 'void';
    if (type.includes('Field')) return 'bigint';
    if (type.includes('Bytes<')) return 'string';
    if (type.includes('Boolean')) return 'boolean';
    if (type.includes('Opaque<"string">')) return 'string';
    if (type.includes('Maybe<')) return `{ is_some: boolean; value: ${this.mapCompactTypeToTS(type.replace(/Maybe<(.*)>/, '$1'))} } | null`;

    return 'any';
  }

  /**
   * Get human-readable type description
   */
  private getTypeDescription(type: string): string {
    if (type === '[]') return 'No return value';
    if (type.includes('Field')) return 'Field element';
    if (type.includes('Bytes<32>')) return '32-byte value';
    if (type.includes('Bytes<')) return 'Byte array';
    if (type.includes('Boolean')) return 'Boolean value';

    return type;
  }

  /**
   * Capitalize first letter
   */
  private capitalize(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }

  /**
   * Generate full workflow example
   */
  private generateFullWorkflowExample(circuits: CircuitInfo[]): string {
    return `// ============================================================================
// Complete Workflow Example
// ============================================================================

/**
 * Complete example: Deploy contract and execute circuits
 */
async function completeWorkflow() {
  console.log('🚀 Starting ${this.contractName} workflow...\\n');

  // 1. Initialize providers
  console.log('1️⃣  Initializing providers...');
  const providers = await initializeProviders();

  // 2. Setup wallet
  console.log('2️⃣  Setting up wallet...');
  const walletProvider = await setupWallet();

  try {
    // 3. Deploy contract
    console.log('3️⃣  Deploying contract...');
    const deployTx = await deployContract(
      walletProvider,
      providers.privateStateProvider,
      contract,
      {}, // Initial state
      providers.publicDataProvider,
      providers.proofProvider
    );

    await providers.nodeProvider.submitTx(deployTx);
    const deployResult = await providers.publicDataProvider.waitForTx(deployTx.txHash);
    const contractAddress = deployResult.contractAddress;

    console.log(\`✅ Contract deployed at: \${contractAddress}\\n\`);

    // 4. Execute circuits
${circuits.slice(0, 3).map((c, i) => `    console.log('${i + 4}️⃣  Calling ${c.name}...');
    await call${this.capitalize(c.name)}(contractAddress, walletProvider${c.params.map(() => ', /* param */').join('')});
    console.log('');`).join('\n\n')}

    console.log('✨ Workflow completed successfully!');

  } catch (error) {
    console.error('❌ Workflow failed:', error);
    throw error;
  } finally {
    await providers.nodeProvider.close();
  }
}

`;
  }

  /**
   * Generate error handling example
   */
  private generateErrorHandlingExample(): string {
    return `// ============================================================================
// Error Handling
// ============================================================================

/**
 * Robust circuit call with error handling
 */
async function callCircuitWithErrorHandling(
  circuit: string,
  args: any
): Promise<any> {
  const providers = await initializeProviders();

  try {
    // Attempt circuit call with retry logic
    const maxRetries = 3;
    let lastError: Error | null = null;

    for (let attempt = 1; attempt <= maxRetries; attempt++) {
      try {
        const tx = await createBalancedTx(
          walletProvider,
          providers.privateStateProvider,
          { type: 'call-circuit', circuit, args },
          providers.publicDataProvider,
          providers.proofProvider
        );

        await providers.nodeProvider.submitTx(tx);
        const result = await providers.publicDataProvider.waitForTx(tx.txHash);

        return result.output;

      } catch (error) {
        lastError = error as Error;
        console.warn(\`Attempt \${attempt}/\${maxRetries} failed: \${error.message}\`);

        if (attempt < maxRetries) {
          // Exponential backoff
          await new Promise(resolve => setTimeout(resolve, 1000 * Math.pow(2, attempt)));
        }
      }
    }

    throw new Error(\`Circuit call failed after \${maxRetries} attempts: \${lastError?.message}\`);

  } catch (error) {
    if (error.message.includes('insufficient funds')) {
      console.error('❌ Insufficient DUST balance');
    } else if (error.message.includes('assertion failed')) {
      console.error('❌ Circuit assertion failed - check preconditions');
    } else if (error.message.includes('timeout')) {
      console.error('❌ Proof generation timeout - circuit may be too complex');
    } else {
      console.error('❌ Unexpected error:', error);
    }

    throw error;
  } finally {
    await providers.nodeProvider.close();
  }
}

`;
  }

  /**
   * Generate testing example
   */
  private generateTestingExample(circuit: CircuitInfo): string {
    return `// ============================================================================
// Testing
// ============================================================================

/**
 * Unit test example using Jest
 */
describe('${this.contractName} Contract', () => {
  let contractAddress: ContractAddress;
  let walletProvider: WalletProvider;
  let providers: Awaited<ReturnType<typeof initializeProviders>>;

  beforeAll(async () => {
    providers = await initializeProviders();
    walletProvider = await setupWallet();

    // Deploy contract for testing
    const deployTx = await deployContract(
      walletProvider,
      providers.privateStateProvider,
      contract,
      {},
      providers.publicDataProvider,
      providers.proofProvider
    );

    await providers.nodeProvider.submitTx(deployTx);
    const result = await providers.publicDataProvider.waitForTx(deployTx.txHash);
    contractAddress = result.contractAddress;
  });

  afterAll(async () => {
    await providers.nodeProvider.close();
  });

  test('should call ${circuit.name} successfully', async () => {
    ${this.generateParamExamples(circuit.params)}

    const result = await call${this.capitalize(circuit.name)}(
      contractAddress,
      walletProvider${circuit.params.map(p => `,\n      ${p.name}`).join('')}
    );

    expect(result).toBeDefined();
    // Add more assertions based on expected behavior
  });

  test('should fail with invalid parameters', async () => {
    await expect(
      call${this.capitalize(circuit.name)}(
        contractAddress,
        walletProvider${circuit.params.map(() => ',\n        null as any').join('')}
      )
    ).rejects.toThrow();
  });
});

// ============================================================================
// Utility Functions
// ============================================================================

/**
 * Setup wallet provider
 * Replace with actual wallet initialization
 */
async function setupWallet(): Promise<WalletProvider> {
  // TODO: Initialize wallet with seed phrase or private key
  throw new Error('Wallet setup not implemented');
}

// ============================================================================
// Run Examples
// ============================================================================

// Uncomment to run specific examples:
// example${this.capitalize(circuit.name)}().catch(console.error);
// completeWorkflow().catch(console.error);
`;
  }
}
